notifications:
  email:
    - shankar.tester901@gmail.com
language: node_js
node_js:
  - 8
install:
  - npm install -g zcatalyst-cli
jobs:
  include:
    - stage: unit tests
      before_script:
        - echo 'applogic testing!!'
        - cd applogic/chuck_norris_jokes
      script:
        - echo 'Installing Deps!'
        - npm install
        - echo 'Testing using mocha chai'
        - npm test
      after_success:
        - echo 'deploying!!!'
        - catalyst deploy --project 1788000000011017
      